site_name: Mothership
site_url: https://binaryman32.github.io/mothership-2025
repo_url: https://github.com/BinaryMan32/mothership-2025
edit_uri: edit/main/docs/
extra_css:
  - stylesheets/extra.css
watch:
  - main.py
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
  palette:
    scheme: slate
    primary: green
    accent: light green
  icon:
    edit: material/lead-pencil
    # https://squidfunk.github.io/mkdocs-material/setup/changing-the-logo-and-icons/#logo-icon-bundled
    logo: fontawesome/solid/shuttle-space
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - navigation.indexes
    - navigation.tabs
    - navigation.tracking
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.betterem
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tilde
  - toc:
      permalink: true
plugins:
  - macros:
      include_dir: include
  - autolinks
  - backlinks_section:
      ignore_links_to:
        - journal/*.md
        - journal/posts/*.md
        - journal/posts/*/*.md
  - blog:
      blog_dir: journal
      categories_allowed: []
  - search
  - tags
validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn
